-- Generated by Mocodo 4.3.2

CREATE TABLE PICTURE (
  PRIMARY KEY (code),
  code             VARCHAR(42) NOT NULL,
  before_Url       VARCHAR(42),
  before_Public_Id VARCHAR(42),
  after_Url        VARCHAR(42),
  after_Public_Id  VARCHAR(42),
  position         VARCHAR(42)
);
